### ISSUE TITLE
domains invalid!

### ISSUE THREAD

**Issue by host24space** [pirat28/iLoveEasyList#1]
[i] Target: https://raw.githubusercontent.com/pirat28/iLoveEasyList/master/CleanEasyLists.txt
  [✓] Status: Retrieval successful
  [i] Received 40245 domains, 3 domains invalid!
      Sample of invalid domains:
      - 2txt.cc:8862
      - 63xs.com:8016
      - xuehongxs.com:8862

**Comment by pirat28** [comment]
Thanks a lot.
I updated + optimized my little converter (convert-EL.sh).
